### ISSUE TITLE
Holiday break texture

### ISSUE THREAD

**Issue by ghost** [TechnoVisionDev/IronChest#7]
Might want to change the holiday break texture as it's copied from expanded storage and is as far as I am aware is licensed under All Rights Reserved as it was provided by Yoghurt4c and was not made by me.

Curseforge page also shows the Christmas chest from expanded storage which should show the vanilla holiday chest instead.

**Comment by TechnoVisionDev** [comment]
A direct quote from the Expanded Storage curseforge "contributors" page, referring to Yoghurt4C pumpkin/christmas chest textures:
"Yoghurt4C, These are released into public domain, feel free to use them in any way you wish even in other mods."

I only used the the Christmas chest break texture and crafting image because you yourself specified that it was okay. If that is no longer the case then you should definitely update your curseforge page.

**Comment by ghost** [comment]
Yoghurt never actually specified that for the Christmas textures but I messaged them last night and they have said that texture should have also been made public domain so I'm going to updated my curseforge page to reflect that.

If you don't use it in-game other than the break texture then it still might be a good idea to update the curseforge page in case anyone gets confused.

Will close this in any case as I guess it wasn't an issue to begin with.
